# Generated by Django 4.0.3 on 2022-03-17 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_course_delete_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
