# Generated by Django 4.0.3 on 2022-03-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_course_user_student_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.ManyToManyField(to='homepage.coursename'),
        ),
    ]
