# Generated by Django 4.0.3 on 2022-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_course_name_course_name_remove_course_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semsester',
        ),
        migrations.CreateModel(
            name='coursegrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semsester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='homepage.course')),
                ('student', models.ManyToManyField(to='homepage.student')),
            ],
        ),
    ]
