# Generated by Django 4.0.3 on 2022-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_course_grade_remove_course_semsester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.ManyToManyField(null=True, to='homepage.course'),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='semsester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='student',
            field=models.ManyToManyField(null=True, to='homepage.student'),
        ),
    ]
