# Generated by Django 4.0.3 on 2022-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_course_year_delete_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
